import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarToggler from "@/components/NavbarToggler/NavbarToggler";
import { currUser } from "@/lib/actions";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await currUser();

	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<div
					style={{
						minHeight: "100vh",
						display: "flex",
						flexDirection: "column",
					}}
				>
					<NavbarToggler user={user} />

					{children}
				</div>
			</body>
		</html>
	);
}
