export const clothingCategories = {
	men: [
		"blazer",
		"boots",
		"cargo pants",
		"chinos",
		"coat",
		"dress shoes",
		"hoodie",
		"jacket",
		"jeans",
		"shirt",
		"shorts",
		"sneakers",
		"sweatshirt",
		"t-shirt",
		"trousers",
	],
	women: [
		"blouse",
		"bodysuit",
		"boots",
		"cardigan",
		"coat",
		"dress",
		"flats",
		"heels",
		"jacket",
		"jeans",
		"jumpsuit",
		"leggings",
		"loafers",
		"romper",
		"sandals",
		"shirt",
		"skirt",
		"sneakers",
		"sweater",
		"t-shirt",
		"trousers",
	],
	unisex: [
		"boots",
		"cardigan",
		"coat",
		"jacket",
		"jeans",
		"loafers",
		"sandals",
		"shirt",
		"shorts",
		"sneakers",
		"sweater",
		"t-shirt",
		"trousers",
	],
};

export const typesOfClothes = [
	"bodysuit",
	"blazer",
	"blouse",
	"boots",
	"cardigan",
	"chinos",
	"coat",
	"cargo pants",
	"dress shoes",
	"dress",
	"flats",
	"heels",
	"hoodie",
	"jeans",
	"jacket",
	"jumpsuit",
	"leggings",
	"loafers",
	"romper",
	"sandals",
	"shirt",
	"shorts",
	"sneakers",
	"sweater",
	"sweatshirt",
	"t-shirt",
	"trousers",
	"vest",
];

export const conditionsOfClothes = ["Brand new", "Pre-owned", "Restored"];
export const sizeOfClothes = ["XS", "S", "M", "L", "XL", "XXL"];
export const sizeOfPants = [
	"w- EU 32",
	"w- EU 34",
	"w- EU 36",
	"w- EU 38",
	"w- EU 40",
	"w- EU 42",
	"w- EU 44",
	"w- EU 46",
	"w- EU 48",
	"w- EU 50",
	"w- EU 52",
	"w- EU 54",
	"w- EU 56",
	"w- EU 58",
	"w- EU 60",
];
export const sizeOfShoes = [
	"EU 35",
	"EU 36",
	"EU 37",
	"EU 38",
	"EU 39",
	"EU 40",
	"EU 41",
	"EU 42",
	"EU 43",
	"EU 44",
	"EU 45",
	"EU 46",
	"EU 47",
	"EU 48",
	"EU 49",
	"EU 50",
];

export const clothesWithSizes = [
	{ type: "bodysuit", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "blazer",
		sizes: ["XS", "S", "M", "L", "XL", "XXL"],
	},
	{ type: "blouse", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "boots",
		sizes: [
			"EU 35",
			"EU 36",
			"EU 37",
			"EU 38",
			"EU 39",
			"EU 40",
			"EU 41",
			"EU 42",
			"EU 43",
			"EU 44",
			"EU 45",
			"EU 46",
			"EU 47",
			"EU 48",
			"EU 49",
			"EU 50",
		],
	},
	{ type: "cardigan", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "chinos",
		sizes: [
			"w- EU 32",
			"w- EU 34",
			"w- EU 36",
			"w- EU 38",
			"w- EU 40",
			"w- EU 42",
			"w- EU 44",
			"w- EU 46",
			"w- EU 48",
			"w- EU 50",
			"w- EU 52",
			"w- EU 54",
			"w- EU 56",
			"w- EU 58",
			"w- EU 60",
		],
	},
	{ type: "coat", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "cargo pants",
		sizes: [
			"w- EU 32",
			"w- EU 34",
			"w- EU 36",
			"w- EU 38",
			"w- EU 40",
			"w- EU 42",
			"w- EU 44",
			"w- EU 46",
			"w- EU 48",
			"w- EU 50",
			"w- EU 52",
			"w- EU 54",
			"w- EU 56",
			"w- EU 58",
			"w- EU 60",
		],
	},
	{
		type: "dress shoes",
		sizes: [
			"EU 35",
			"EU 36",
			"EU 37",
			"EU 38",
			"EU 39",
			"EU 40",
			"EU 41",
			"EU 42",
			"EU 43",
			"EU 44",
			"EU 45",
			"EU 46",
			"EU 47",
			"EU 48",
			"EU 49",
			"EU 50",
		],
	},
	{ type: "dress", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "flats",
		sizes: [
			"EU 35",
			"EU 36",
			"EU 37",
			"EU 38",
			"EU 39",
			"EU 40",
			"EU 41",
			"EU 42",
			"EU 43",
			"EU 44",
			"EU 45",
			"EU 46",
			"EU 47",
			"EU 48",
			"EU 49",
			"EU 50",
		],
	},
	{
		type: "heels",
		sizes: [
			"EU 35",
			"EU 36",
			"EU 37",
			"EU 38",
			"EU 39",
			"EU 40",
			"EU 41",
			"EU 42",
			"EU 43",
			"EU 44",
			"EU 45",
			"EU 46",
			"EU 47",
			"EU 48",
			"EU 49",
			"EU 50",
		],
	},
	{
		type: "jeans",
		sizes: [
			"w- EU 32",
			"w- EU 34",
			"w- EU 36",
			"w- EU 38",
			"w- EU 40",
			"w- EU 42",
			"w- EU 44",
			"w- EU 46",
			"w- EU 48",
			"w- EU 50",
			"w- EU 52",
			"w- EU 54",
			"w- EU 56",
			"w- EU 58",
			"w- EU 60",
		],
	},
	{ type: "jacket", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{ type: "jumpsuit", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "loafers",
		sizes: [
			"EU 35",
			"EU 36",
			"EU 37",
			"EU 38",
			"EU 39",
			"EU 40",
			"EU 41",
			"EU 42",
			"EU 43",
			"EU 44",
			"EU 45",
			"EU 46",
			"EU 47",
			"EU 48",
			"EU 49",
			"EU 50",
		],
	},
	{ type: "romper", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "sandals",
		sizes: [
			"EU 35",
			"EU 36",
			"EU 37",
			"EU 38",
			"EU 39",
			"EU 40",
			"EU 41",
			"EU 42",
			"EU 43",
			"EU 44",
			"EU 45",
			"EU 46",
			"EU 47",
			"EU 48",
			"EU 49",
			"EU 50",
		],
	},
	{ type: "shirt", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "shorts",
		sizes: [
			"w- EU 32",
			"w- EU 34",
			"w- EU 36",
			"w- EU 38",
			"w- EU 40",
			"w- EU 42",
			"w- EU 44",
			"w- EU 46",
			"w- EU 48",
			"w- EU 50",
			"w- EU 52",
			"w- EU 54",
			"w- EU 56",
			"w- EU 58",
			"w- EU 60",
		],
	},
	{
		type: "sneakers",
		sizes: [
			"EU 35",
			"EU 36",
			"EU 37",
			"EU 38",
			"EU 39",
			"EU 40",
			"EU 41",
			"EU 42",
			"EU 43",
			"EU 44",
			"EU 45",
			"EU 46",
			"EU 47",
			"EU 48",
			"EU 49",
			"EU 50",
		],
	},
	{ type: "sweater", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{ type: "sweatshirt", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{ type: "t-shirt", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "trousers",
		sizes: [
			"w- EU 32",
			"w- EU 34",
			"w- EU 36",
			"w- EU 38",
			"w- EU 40",
			"w- EU 42",
			"w- EU 44",
			"w- EU 46",
			"w- EU 48",
			"w- EU 50",
			"w- EU 52",
			"w- EU 54",
			"w- EU 56",
			"w- EU 58",
			"w- EU 60",
		],
	},
	{ type: "vest", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
];

export const clothingGenders = ["men", "women", "unisex"];
type Gender = (typeof clothingGenders)[number];

export const allSizes = sizeOfClothes.concat(sizeOfPants, sizeOfShoes);

const getRandom = (arr: any) => arr[Math.floor(Math.random() * arr.length)];

function generateClothingItems(count = 30) {
	const items = [];

	for (let i = 0; i < count; i++) {
		const gender = getRandom(clothingGenders) as Gender;
		const type = getRandom(clothingCategories[gender]);
		const sizesForType = clothesWithSizes.find(
			(item) => item.type === type
		)?.sizes;

		let size;
		if (sizesForType && sizesForType.length > 0) {
			size = getRandom(sizesForType);
		} else {
			size = getRandom(["XS", "S", "M", "L", "XL", "XXL"]);
		}

		const condition = getRandom(conditionsOfClothes);
		const price = +(Math.random() * 200 + 10).toFixed(2);
		const negotiablePrice = Math.random() < 0.5;

		items.push({
			type,
			name: `${gender} ${type}`,
			price,
			description: `A ${condition.toLowerCase()} ${type} for ${gender}. Size: ${size}.`,
			negotiablePrice,
			condition,
			size,
			gender,
		});
	}

	return items;
}

export const clothes = generateClothingItems(50);
