export const typesOfClothes = [
	"t-shirt",
	"jeans",
	"pants",
	"skirt",
	"hoodie",
	"jacket",
	"shorts",
	"dress",
	"shoes",
];
export const conditionsOfClothes = ["Brand new", "Pre-owned", "Restored"];
export const sizeOfClothes = ["XS", "S", "M", "L", "XL", "XXL"];
export const sizeOfPants = ["32", "34", "36", "38", "40", "42", "44", "46"];
export const sizeOfShoes = [
	"35",
	"36",
	"37",
	"38",
	"39",
	"40",
	"41",
	"42",
	"43",
	"44",
	"45",
	"46",
];

export const sizeMap: Record<string, string[]> = {
	shoes: sizeOfShoes,
	jeans: sizeOfPants,
	pants: sizeOfPants,
	shorts: sizeOfPants,
	default: sizeOfClothes,
};

export const clothesWithSizes = [
	{ type: "t-shirt", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{ type: "jeans", sizes: ["32", "34", "36", "38", "40", "42", "44", "46"] },
	{ type: "pants", sizes: ["32", "34", "36", "38", "40", "42", "44", "46"] },
	{ type: "skirt", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{ type: "hoodie", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{ type: "jacket", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{ type: "shorts", sizes: ["32", "34", "36", "38", "40", "42", "44", "46"] },
	{ type: "dress", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
	{
		type: "shoes",
		sizes: [
			"35",
			"36",
			"37",
			"38",
			"39",
			"40",
			"41",
			"42",
			"43",
			"44",
			"45",
			"46",
		],
	},
];
// const clothesWithSizes = typesOfClothes.map((type) => ({
// 	type,
// 	sizes: sizeMap[type] || sizeMap.default,
// }));

export const allSizes = sizeOfClothes.concat(sizeOfPants, sizeOfShoes);

export const clothes = [
	{
		type: "t-shirt",
		name: "Casual Tee",
		price: 20,
		description: "Slim black t-shirt with angel on the back",
		negotiablePrice: true,
		condition: "Brand new",
		size: "M",
	},
	{
		type: "jeans",
		name: "Classic Blue Jeans",
		price: 40,
		description: "Comfortable straight-fit denim jeans",
		negotiablePrice: false,
		condition: "Pre-owned",
		size: "34",
	},
	{
		type: "pants",
		name: "Office Slacks",
		price: 35,
		description: "Black formal pants perfect for work",
		negotiablePrice: true,
		condition: "Brand new",
		size: "36",
	},
	{
		type: "skirt",
		name: "Floral Midi Skirt",
		price: 25,
		description: "Light floral pattern, soft fabric feel",
		negotiablePrice: false,
		condition: "Restored",
		size: "S",
	},
	{
		type: "hoodie",
		name: "Oversized Hoodie",
		price: 45,
		description: "Cozy oversized hoodie with front pocket",
		negotiablePrice: true,
		condition: "Brand new",
		size: "L",
	},
	{
		type: "jacket",
		name: "Denim Jacket",
		price: 50,
		description: "Vintage wash denim jacket with pockets",
		negotiablePrice: true,
		condition: "Pre-owned",
		size: "M",
	},
	{
		type: "shorts",
		name: "Cargo Shorts",
		price: 22,
		description: "Beige cargo shorts with side pockets",
		negotiablePrice: false,
		condition: "Restored",
		size: "40",
	},
	{
		type: "dress",
		name: "Evening Dress",
		price: 70,
		description: "Elegant long black dress for events",
		negotiablePrice: true,
		condition: "Brand new",
		size: "M",
	},
	{
		type: "shoes",
		name: "Running Sneakers",
		price: 60,
		description: "Breathable and cushioned running shoes",
		negotiablePrice: false,
		condition: "Pre-owned",
		size: "42",
	},
	{
		type: "t-shirt",
		name: "Graphic Tee",
		price: 18,
		description: "Colorful tee with unique skull artwork",
		negotiablePrice: true,
		condition: "Restored",
		size: "L",
	},
	{
		type: "jeans",
		name: "Skinny Fit Jeans",
		price: 38,
		description: "Dark wash skinny jeans with stretch",
		negotiablePrice: true,
		condition: "Brand new",
		size: "32",
	},
	{
		type: "pants",
		name: "Chino Pants",
		price: 30,
		description: "Khaki slim-fit chinos for casual wear",
		negotiablePrice: false,
		condition: "Pre-owned",
		size: "38",
	},
	{
		type: "skirt",
		name: "Denim Mini Skirt",
		price: 20,
		description: "Frayed denim skirt for everyday style",
		negotiablePrice: true,
		condition: "Brand new",
		size: "XS",
	},
	{
		type: "hoodie",
		name: "Zip-up Hoodie",
		price: 40,
		description: "Gray hoodie with zip and fleece lining",
		negotiablePrice: false,
		condition: "Restored",
		size: "XL",
	},
	{
		type: "jacket",
		name: "Bomber Jacket",
		price: 55,
		description: "Military-style bomber jacket, water-resistant",
		negotiablePrice: true,
		condition: "Pre-owned",
		size: "L",
	},
	{
		type: "shorts",
		name: "Denim Shorts",
		price: 19,
		description: "Light blue denim shorts with rolled cuffs",
		negotiablePrice: false,
		condition: "Brand new",
		size: "36",
	},
	{
		type: "dress",
		name: "Summer Sundress",
		price: 33,
		description: "Lightweight sundress with floral print",
		negotiablePrice: true,
		condition: "Brand new",
		size: "S",
	},
	{
		type: "shoes",
		name: "Leather Boots",
		price: 80,
		description: "Durable brown leather boots for fall",
		negotiablePrice: true,
		condition: "Pre-owned",
		size: "43",
	},
	{
		type: "t-shirt",
		name: "Striped Tee",
		price: 17,
		description: "Black and white striped short-sleeve tee",
		negotiablePrice: false,
		condition: "Brand new",
		size: "S",
	},
	{
		type: "jeans",
		name: "Ripped Jeans",
		price: 42,
		description: "Stylish jeans with rips at the knees",
		negotiablePrice: true,
		condition: "Restored",
		size: "40",
	},
	{
		type: "pants",
		name: "Jogger Pants",
		price: 28,
		description: "Comfortable joggers with drawstring waist",
		negotiablePrice: false,
		condition: "Pre-owned",
		size: "34",
	},
	{
		type: "skirt",
		name: "Pleated Skirt",
		price: 27,
		description: "Navy blue pleated skirt for formal wear",
		negotiablePrice: true,
		condition: "Brand new",
		size: "M",
	},
	{
		type: "hoodie",
		name: "Color Block Hoodie",
		price: 48,
		description: "Trendy hoodie with contrasting color panels",
		negotiablePrice: false,
		condition: "Restored",
		size: "XXL",
	},
	{
		type: "jacket",
		name: "Puffer Jacket",
		price: 65,
		description: "Warm padded puffer jacket for winter",
		negotiablePrice: true,
		condition: "Brand new",
		size: "XL",
	},
	{
		type: "shoes",
		name: "Slip-On Shoes",
		price: 35,
		description: "Comfy canvas slip-ons for everyday use",
		negotiablePrice: false,
		condition: "Restored",
		size: "41",
	},
];
